# Generated by Django 5.0.2 on 2024-03-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "bookId",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("bookTitle", models.CharField(max_length=100)),
                ("bookAuthor", models.CharField(max_length=100)),
                ("bookPublisher", models.CharField(max_length=100)),
                ("bookEdition", models.CharField(max_length=100)),
                ("bookForm", models.CharField(max_length=100)),
                ("bookSubject", models.CharField(max_length=100)),
                ("bookCondition", models.CharField(max_length=100)),
                ("dateAdded", models.DateField()),
                ("addedBy", models.CharField(max_length=100)),
            ],
        ),
    ]
