# Generated by Django 5.0.2 on 2024-03-03 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Books",
            new_name="Book_Reg",
        ),
    ]
