# Generated by Django 5.0.2 on 2024-03-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_issued_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book_reg",
            name="bookId",
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="book_reg",
            name="bookTitle",
            field=models.CharField(max_length=150),
        ),
    ]
