# Generated by Django 5.0.2 on 2024-03-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_book_reg_bookid_alter_book_reg_booktitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issued_book",
            name="bookCondition",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="issued_book",
            name="bookTitle",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="issued_book",
            name="issuedBy",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="issued_book",
            name="studentId",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="issued_book",
            name="studentName",
            field=models.CharField(max_length=200),
        ),
    ]
