# Generated by Django 5.0.2 on 2024-03-04 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_issued_book_bookcondition_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Issued_Book",
            new_name="Borrowed_Books",
        ),
    ]
