# Generated by Django 5.0.2 on 2024-03-04 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_rename_issued_book_borrowed_books"),
    ]

    operations = [
        migrations.CreateModel(
            name="LostBooks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bookTitle", models.CharField(max_length=200)),
                ("studentId", models.CharField(max_length=200)),
                ("studentName", models.CharField(max_length=200)),
                ("bookFine", models.CharField(max_length=200)),
                ("filledBy", models.CharField(max_length=200)),
                (
                    "bookId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.book_reg"
                    ),
                ),
            ],
        ),
    ]
