# Generated by Django 4.2.11 on 2024-03-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_lostbooks"),
    ]

    operations = [
        migrations.AddField(
            model_name="book_reg",
            name="bookStatus",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
