# Generated by Django 4.2.11 on 2024-03-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_book_reg_bookstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userName", models.CharField(max_length=200)),
                ("userPassword", models.CharField(max_length=200)),
            ],
        ),
    ]
